# Generated by Django 2.0.13 on 2019-06-20 13:10

from django.db import migrations, models
import django.db.models.deletion
import imperavi.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('keywords', models.TextField(blank=True, default='', help_text='Через запятую, без пробелов.', verbose_name='Ключевики')),
                ('menu_title', models.CharField(blank=True, help_text='если не указано – будет, как заголовок страницы', max_length=255, null=True, verbose_name='Название в меню')),
                ('banner', models.ForeignKey(blank=True, help_text='Также используется как изображение для шаринга страницы в соцсетях', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': '_Служебная – Пустая страница',
                'verbose_name_plural': '_Служебная – Пустая страница',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('keywords', models.TextField(blank=True, default='', help_text='Через запятую, без пробелов.', verbose_name='Ключевики')),
                ('menu_title', models.CharField(blank=True, help_text='если не указано – будет, как заголовок страницы', max_length=255, null=True, verbose_name='Название в меню')),
                ('banner', models.ForeignKey(blank=True, help_text='Также используется как изображение для шаринга страницы в соцсетях', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Баннер')),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Перенаправить на страницу')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страницы',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок по-умолчанию')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание по-умолчанию')),
                ('keywords', models.TextField(blank=True, help_text='через запятую, без пробелов', null=True, verbose_name='Ключевики по-умолчанию')),
                ('footer', imperavi.fields.RedactorField(blank=True, null=True, verbose_name='Футер')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Баннер по умолчанию')),
                ('root_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Корневая страница')),
                ('search_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Страницы поиска')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='blankpage',
            name='redirect_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Перенаправить на страницу'),
        ),
    ]
