# Generated by Django 2.0.13 on 2019-06-27 10:14

from django.db import migrations, models
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('images', wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Картинка'))], verbose_name='Картинки')),
            ],
            options={
                'verbose_name': 'гелерею',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
