# Generated by Django 2.0.13 on 2019-06-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gallerypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='core.Gallery', verbose_name='Галерея'),
        ),
    ]
