# Generated by Django 2.0.13 on 2019-06-27 13:27

import core.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190627_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', core.blocks.EditableBlock()), ('youtube', core.blocks.YoutubeBlock()), ('image', core.blocks.SimpleImageBlock()), ('gallery_list', core.blocks.GalleryList())], blank=True, null=True, verbose_name='Контент'),
        ),
    ]
