# Generated by Django 2.0.13 on 2019-06-28 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bloglistpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticlePage')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Блог –  Запись',
                'verbose_name_plural': 'Блог –  Запись',
            },
            bases=('core.articlepage',),
        ),
    ]
