# Generated by Django 2.0.13 on 2019-07-01 10:46

from django.db import migrations
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190701_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewslist',
            name='reviews',
            field=wagtail.core.fields.StreamField([('review', wagtail.snippets.blocks.SnippetChooserBlock('core.Review', icon='plus', label='Отзыв'))], blank=True, null=True, verbose_name='Отзывы'),
        ),
    ]
