# Generated by Django 2.0.13 on 2019-07-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reviewslist_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='name',
        ),
    ]
