# Generated by Django 2.0.13 on 2019-07-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190701_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='message',
        ),
    ]
