# Generated by Django 2.0.13 on 2019-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190701_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='root_page',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='search_page',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='disfo',
            field=models.URLField(blank=True, default='http://disfo.ru/profile/Axlnick/', null=True, verbose_name='Disfo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='fb',
            field=models.URLField(blank=True, default='https://web.facebook.com/groups/opirogova/', null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ig',
            field=models.URLField(blank=True, default='https://instagram.com/olesyapirogova/', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='vk',
            field=models.URLField(blank=True, default='http://vk.com/o_pirogova', null=True, verbose_name='VK'),
        ),
    ]
