# Generated by Django 2.0.13 on 2019-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190701_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='anal',
            field=models.TextField(blank=True, null=True, verbose_name='Код аналитики'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='verification',
            field=models.TextField(blank=True, null=True, verbose_name='Код верификации'),
        ),
    ]
